// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAizAlIV5L6vjqpmx00ewUH9lUA_kMUrMc',
    appId: '1:287455002300:web:2024b8aaa3fc4a0e439ab9',
    messagingSenderId: '287455002300',
    projectId: 'flutter-sharesched',
    authDomain: 'flutter-sharesched.firebaseapp.com',
    storageBucket: 'flutter-sharesched.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuuPYkxnkRcgxxRKk68j2HWgZBCNtcVXg',
    appId: '1:287455002300:android:40231241546c6908439ab9',
    messagingSenderId: '287455002300',
    projectId: 'flutter-sharesched',
    storageBucket: 'flutter-sharesched.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2O5r_xQpMZ6I-069ByVNlgFs0o89nUVU',
    appId: '1:287455002300:ios:a3dc6fa4a6cad3ba439ab9',
    messagingSenderId: '287455002300',
    projectId: 'flutter-sharesched',
    storageBucket: 'flutter-sharesched.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2O5r_xQpMZ6I-069ByVNlgFs0o89nUVU',
    appId: '1:287455002300:ios:a3dc6fa4a6cad3ba439ab9',
    messagingSenderId: '287455002300',
    projectId: 'flutter-sharesched',
    storageBucket: 'flutter-sharesched.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
